# environment version 3, updated Mar. 5, 2021
# note: pytorch is a relatively large download, at least on windows
name: cs538-nogpu
channels:
#- pytorch
- conda-forge
- default
dependencies:
- python=3.8
- pip
- pandas
- scipy
- tbb
- lenskit>=0.12
- scikit-learn
- tqdm
- matplotlib
- seaborn
- notebook
# - jupyterlab
- ipywidgets
- tensorflow>=2.3
- docopt
- scikit-optimize
- pip:
  - torch